[tool.poetry]
name = "poetry-web"
version = "0.1.0"
description = ""
authors = ["Jukka Aho <ahojukka5@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
